@startuml
class ERC20
class token
class "supervise" as supervise {
	generator
	supervisor
	creditToPay[address=>uint]
	setCreditToPay mustSupervisor(address, uint)
	sendCredit mustSupervisor(address, uint)
	setSupervisor mustGenerator(address)
	modifier mustGenerator()
	modifier mustSupervisor()
	modifier mustPay()
}
class "traceability" as trace {
	objects[id=>object]
	mustOwner()
	create mustOwner (sources[])
	push mustPay()
	pull()
	destroy mustSupervisor()
}
class "object" as object {
	materials[]
	owner
	preOwners[]
	credits[address=>uint]
	receiver
}

ERC20 <|- token
token <|- supervise
supervise <|- trace
trace *-- object
@enduml