@startuml
class "traceability" as trace {
	objects[]
	roles[]
	create()
	destroy()
}
class "role" as role {
	name
	getName()
	setName()
}
class "certification" as cert {
	certifyer
	requirer
	time
}
class "object" as obj {
	parents[]
	certifications[]
	owners[]
	pushTo
	pullFrom
	push()
	pull()
}

trace *-- obj
trace *-- role
obj *-- cert
obj *-- role
cert *-- role
@enduml