@startuml
actor "supervisor" as supervisor
actor "material vendor" as vendor
actor "manufactor" as manufactor
actor "distributor" as distributor
actor "retailer" as retailer
actor "consumer" as consumer
rectangle {
	usecase "credit，deduction，restitution of token" as supervise
	usecase "Create, Push" as createMaterial
	usecase "Pull, Create, Push" as createPig
	usecase "Pull, Create, Push" as createBody
	usecase "Pull, Create, Push" as createPork
	usecase "Pull" as consume 
	rectangle "Goods" as goods {
		together {
			component "feed, drugs" as material
			component "pig" as pig
			component "body" as body
			component "pork" as pork
		}
		database "credit token when push" as token
		material .down. pig
		pig .down. body
		body .down. pork
	}
}

usecase "complaint, submit evidence" as complaint
consumer->complaint
complaint-->supervisor

supervisor-down->supervise
supervise-down->token

vendor-right->createMaterial
createMaterial-right->material

material-right->createPig
manufactor-right->createPig
createPig-right->pig

pig-right->createBody 
distributor-right->createBody 
createBody-right->body

body-right->createPork
retailer-right->createPork
createPork-right->pork

pork-left->consume
consume-left->consumer
@enduml